files:
  clinical: "C:/Users/DAVID/Downloads/hla-covid-analisis/data/raw/DatosP.txt"
  model: "C:/Users/DAVID/Downloads/hla-covid-analisis/data/raw/Human660W-Hispanic-HLA4-hg19.RData"
  genetic: "C:/Users/DAVID/Downloads/hla-covid-analisis/data/raw/LA_HLA_Region"
  log_file: "logs/analysis.log"

directories:
  results: "results"
  plots: "plots"
  logs: "logs"

analysis_params:
  min_freq: 10
  required_vars: ["R_SEV4", "R_HOSP", "ASINT"]
  p_threshold: 0.05

report_params:
  include_plots: true
  include_tables: true
  confidence_level: 0.95